### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by linsui** [Kiteio/Punica-old-android#1]
请问可以发布到 F-Droid 吗？

**Comment by chanwingchow** [comment]
应该不会（没什么经验，看着很麻烦），我到时候会做软件内的版本升级。

**Comment by linsui** [comment]
没关系，我有经验 :rofl:

**Comment by chanwingchow** [comment]
> 没关系，我有经验 🤣

软件是 MIT 开源的，我不会管任何的二次发布，你可以随意，我有点懒（doge）。

**Comment by linsui** [comment]
好，有问题我再请教 :+1:
