### ISSUE TITLE
引入 VPN 方便校外访问

### ISSUE THREAD

**Issue by Xukai2** [Kiteio/Punica-old-android#2]
emmmmmm，就个人觉得啊，我觉得这个已经做的很棒了，毕竟广财都没有这个东西，不过软件内只有能连接校园网的，如果我不在学校内就连接不了校园网，所以我觉得如果能加一个vpn就更完美了，不过不着急，我觉得现在这个已经很厉害了，为作者点个大大的赞

**Comment by chanwingchow** [comment]
感谢👍。在之前我已经做了相关的功能（[参照](https://github.com/Kiteio/Punica/commit/1277e32bb2a77960ea913a505caff3c5c6b9ce79)），但是 WebVPN 被学校加了短信/临时码验证，这也是最近的事。我需要花点时间考量它的必要性（每次登录都必须输入短信验证码/临时码，并且请求过程比连接校园网慢），来决定要不要破译它。

**Comment by chanwingchow** [comment]
算了，各种缘故，这个就放掉了。
