### ISSUE TITLE
开学日期不对

### ISSUE THREAD

**Issue by Xukai2** [Kiteio/Punica-old-android#3]
比如说我点开学日期为9月7号，然后实际显示的却是9月十多号，然后就导致那个日程那边也跟着出错

**Comment by chanwingchow** [comment]
好的，在下个版本会得到修复。

**Comment by chanwingchow** [comment]
我已经创建了一个修复该问题的提交 c3b99eaffa06b7e368fb6089c7501ad688e97479。
另，该日期选择功能会定位到所选日期所在周次的星期一的日期，方便计算周次。
